basefolder = "/tmp"

[[series]]
    key = "thunderbirds"
    filenametemplate = "{{.Series}}/{{.Series}} {{.Season}}{{.Episode}}"
    seriesregexp = ".*"
    seriesreplacement = "Thunderbirds Are Go"
    seasonregexp = "^Säsong ([0-9]+)$"
    seasonreplacement = "S$1"
    episoderegexp = "^Avsnitt ([0-9]+)$"
    episodereplacement = "E$1"
