basefolder = "/tmp"

[[series]]
    key = "thunderbirds"
    filenametemplate = "{{.Series}}/{{.Series}} {{.Season}}{{.Episode}}"

    [series.series]
        regex = ".*"
        replacement = "Thunderbirds Are Go"
    
    [series.season]
        regex = "^Säsong ([0-9]+)$"
        replacement = "S$1"

    [series.episode]
        regex = "^Avsnitt ([0-9]+)$"
        replacement = "E$1"
